name: 2. Create Release

on:
  workflow_run:
    workflows: ["1. Build Mod JAR"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the specific commit that was built
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # --- НОВЫЙ ШАГ: Читаем версию из gradle.properties ---
      - name: Read mod version from gradle.properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: './gradle.properties'
          properties: 'modVersion'

      - name: Create Release Assets Directory
        run: mkdir -p ./release-assets

      - name: Download JAR artifact (only if build succeeded)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow_run_id: ${{ github.event.workflow_run.id }}
          name: PictureToLogicMod
          path: ./release-assets

      - name: Create Source Code ZIP
        run: zip -r ./release-assets/source-code.zip . -x ".git/*" ".github/*" "build/*" ".gradle/*"

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          # ИСПОЛЬЗУЕМ ВЕРСИЮ ИЗ ФАЙЛА
          tag_name: ${{ github.event.workflow_run.conclusion == 'success' && format('v{0}-build.{1}', steps.properties.outputs.modVersion, github.event.workflow_run.run_number) || format('failed-build.{0}', github.event.workflow_run.run_number) }}
          name: "v${{ steps.properties.outputs.modVersion }} Build ${{ github.event.workflow_run.run_number }} (${{ github.event.workflow_run.conclusion }})"
          body: |
            Automatic build from commit ${{ github.event.workflow_run.head_sha }}.
            Build status: **${{ github.event.workflow_run.conclusion }}**
          prerelease: ${{ github.event.workflow_run.conclusion != 'success' }}
          make_latest: ${{ github.event.workflow_run.conclusion == 'success' }}
          files: ./release-assets/*

      - name: Update 'latest' tag to point to this successful build
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "latest"
          sha: ${{ github.event.workflow_run.head_sha }}
          force_push_tag: true
