name: 2. Create Release

on:
  workflow_run:
    workflows: ["1. Build Mod JAR"]
    types:
      - completed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout the specific commit that was built
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Create Release Assets Directory
        run: mkdir -p ./release-assets

      # --- ГЛАВНОЕ ИСПРАВЛЕНИЕ ---
      # Используем action, который умеет скачивать артефакты из ДРУГИХ сборок
      - name: Download JAR artifact (only if build succeeded)
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: dawidd6/action-download-artifact@v3
        with:
          # Указываем ID сборки, из которой нужно скачать
          run_id: ${{ github.event.workflow_run.id }}
          # Имя артефакта, как в build-mod.yml
          name: PictureToLogicMod
          # Указываем, куда его положить
          path: ./release-assets

      - name: Create Source Code ZIP
        run: zip -r ./release-assets/source-code.zip . -x ".git/*" ".github/*" "build/*" ".gradle/*"

      - name: Create/Update GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.workflow_run.conclusion == 'success' && 'latest' || format('failed-{0}', github.event.workflow_run.id) }}
          name: ${{ github.event.workflow_run.conclusion == 'success' && 'Latest Build' || format('Build Failed - Run {0}', github.event.workflow_run.id) }}
          body: "Автоматическая сборка мода. Статус: ${{ github.event.workflow_run.conclusion }}"
          draft: ${{ github.event.workflow_run.conclusion != 'success' }}
          files: ./release-assets/*
